global:
    0x8035a550: __vt__22EnemyStrategyDecorator
    0x8035a574: __vt__13EnemyStrategy
    0x804d2e60: __RTTI__13JORReflexible
    0x804d2e68: __RTTI__13EnemyStrategy
    0x804d2e70: __RTTI__22EnemyStrategyDecorator
    
    0x800c2238: __ct__13EnemyStrategyFv
    0x800c2260: __dt__13EnemyStrategyFv
    0x800c22ac: init__13EnemyStrategyFv
    0x800c22b0: update__13EnemyStrategyFv
    0x800c230c: doBehavior__13EnemyStrategyFv
    0x800c2310: doBehaviorInit__13EnemyStrategyFv
    0x800c2314: FUN_800c1314__13EnemyStrategyFv
    0x800c231c: FUN_800c231c__13EnemyStrategyFv
    0x800c2320: setNextState__13EnemyStrategyFs
    0x800c2328: changeState__13EnemyStrategyFv
    
    0x800c2370: __nw__13EnemyStrategyFUlPv
    0x800c2378: __dl__13EnemyStrategyFPv
    
    0x800c237c: __ct__22EnemyStrategyDecoratorFv
    0x8006b02c: __dt__22EnemyStrategyDecoratorFv
    0x800c23bc: trySetTsuriStrategy__22EnemyStrategyDecoratorFP13EnemyStrategy
    0x800c23dc: update__22EnemyStrategyDecoratorFv
    
    #0x804d632c: __RTTI__Q24Koga14CharacterEvent
    0x800ea1b4: __ct__Q24Koga14CharacterEventFRCi
    
    #0x8034b8ec: __vt__Q24Koga8Observer<Q24Koga14CharacterEvent,b>
    #0x804d1d3c: __RTTI__Q24Koga8Observer<Q24Koga14CharacterEvent,b>
    
    0x80364088: __vt__Q24Koga22CharacterEventObserver
    0x804d3f70: __RTTI__Q24Koga22CharacterEventObserver
    
    0x800ea1dc: receiveMessage__Q24Koga22CharacterEventObserverFPQ24Koga14CharacterEvent
    0x800ea368: onEnteredFlashlightBeam__Q24Koga22CharacterEventObserverFPQ24Koga14CharacterEvent
    0x800ea370: onCaptureBegin__Q24Koga22CharacterEventObserverFPQ24Koga14CharacterEvent
    0x800ea378: onCaptureEnd__Q24Koga22CharacterEventObserverFPQ24Koga14CharacterEvent
    0x800ea380: FUN_800ea380__Q24Koga22CharacterEventObserverFPQ24Koga14CharacterEvent
    0x800ea388: onCollideWithPlayer__Q24Koga22CharacterEventObserverFPQ24Koga14CharacterEvent
    
    0x800ea390: onSprayedWithFire__Q24Koga22CharacterEventObserverFPQ24Koga14CharacterEvent
    0x800ea398: onSprayedWithIce__Q24Koga22CharacterEventObserverFPQ24Koga14CharacterEvent
    0x800ea3a0: onSprayedWithWater__Q24Koga22CharacterEventObserverFPQ24Koga14CharacterEvent
    
    0x800ea3a8: onHitWithFireBall__Q24Koga22CharacterEventObserverFPQ24Koga14CharacterEvent
    0x800ea3d4: onHitWithIceBall__Q24Koga22CharacterEventObserverFPQ24Koga14CharacterEvent
    0x800ea400: onHitWithWaterBall__Q24Koga22CharacterEventObserverFPQ24Koga14CharacterEvent
    
    0x800ea42c: onFishingBegin__Q24Koga22CharacterEventObserverFPQ24Koga14CharacterEvent
    0x800ea434: onPlayerLeftRoom__Q24Koga22CharacterEventObserverFPQ24Koga14CharacterEvent
    0x800ea43c: onPlayerEnteredRoom__Q24Koga22CharacterEventObserverFPQ24Koga14CharacterEvent
    0x800ea444: onPlayerTapped__Q24Koga22CharacterEventObserverFPQ24Koga14CharacterEvent
    0x800ea44c: FUN_800ea44c__Q24Koga22CharacterEventObserverFPQ24Koga14CharacterEvent
    
    # SDK Symbols
    # VI
    0x801e6ee8: __VIRetraceHandler
    0x801e70f8: VISetPreRetraceCallback
    0x801e713c: getTiming
    0x801e71a4: __VIInit
    0x801e738c: VIInit
    0x801e77c0: VIWaitForRetrace
    0x801e7814: setFbbRegs
    0x801e7ae8: setVerticalRegs
    0x801e7c88: VIConfigure
    0x801e8338: VIFlush
    0x801e843c: VISetNextFrameBuffer
    0x801e84a8: VISetBlack
    0x801e8524: VIGetRetraceCount
    0x801e852c: getCurrentFieldEvenOdd
    0x801e85e8: VIGetNextField
    0x801e86dc: VIGetScanMode
    0x801e86e8: VIGetDTVStatus
    