global:
    0x8035a550: __vt__22EnemyStrategyDecorator
    0x8035a574: __vt__13EnemyStrategy
    0x804d2e60: __RTTI__13JORReflexible
    0x804d2e68: __RTTI__13EnemyStrategy
    0x804d2e70: __RTTI__22EnemyStrategyDecorator
    
    0x800c2238: __ct__13EnemyStrategyFv
    0x800c2260: __dt__13EnemyStrategyFv
    0x800c22ac: init__13EnemyStrategyFv
    0x800c22b0: update__13EnemyStrategyFv
    0x800c230c: doBehavior__13EnemyStrategyFv
    0x800c2310: doBehaviorInit__13EnemyStrategyFv
    0x800c2314: FUN_800c1314__13EnemyStrategyFv
    0x800c231c: FUN_800c231c__13EnemyStrategyFv
    0x800c2320: setNextState__13EnemyStrategyFs
    0x800c2328: changeState__13EnemyStrategyFv
    
    0x800c2370: __nw__13EnemyStrategyFUlPv
    0x800c2378: __dl__13EnemyStrategyFPv
    
    0x800c237c: __ct__22EnemyStrategyDecoratorFv
    0x8006b02c: __dt__22EnemyStrategyDecoratorFv
    0x800c23bc: trySetTsuriStrategy__22EnemyStrategyDecoratorFP13EnemyStrategy
    0x800c23dc: update__22EnemyStrategyDecoratorFv
    
    #0x804d632c: __RTTI__Q24Koga14CharacterEvent
    0x800ea1b4: __ct__Q24Koga14CharacterEventFRCi
    
    #0x8034b8ec: __vt__Q24Koga8Observer<Q24Koga14CharacterEvent,b>
    #0x804d1d3c: __RTTI__Q24Koga8Observer<Q24Koga14CharacterEvent,b>
    
    0x80364088: __vt__Q24Koga22CharacterEventObserver
    0x804d3f70: __RTTI__Q24Koga22CharacterEventObserver
    
    0x800ea1dc: receiveMessage__Q24Koga22CharacterEventObserverFPQ24Koga14CharacterEvent
    0x800ea368: onEnteredFlashlightBeam__Q24Koga22CharacterEventObserverFPQ24Koga14CharacterEvent
    0x800ea370: onCaptureBegin__Q24Koga22CharacterEventObserverFPQ24Koga14CharacterEvent
    0x800ea378: onCaptureEnd__Q24Koga22CharacterEventObserverFPQ24Koga14CharacterEvent
    0x800ea380: FUN_800ea380__Q24Koga22CharacterEventObserverFPQ24Koga14CharacterEvent
    0x800ea388: onCollideWithPlayer__Q24Koga22CharacterEventObserverFPQ24Koga14CharacterEvent
    
    0x800ea390: onSprayedWithFire__Q24Koga22CharacterEventObserverFPQ24Koga14CharacterEvent
    0x800ea398: onSprayedWithIce__Q24Koga22CharacterEventObserverFPQ24Koga14CharacterEvent
    0x800ea3a0: onSprayedWithWater__Q24Koga22CharacterEventObserverFPQ24Koga14CharacterEvent
    
    0x800ea3a8: onHitWithFireBall__Q24Koga22CharacterEventObserverFPQ24Koga14CharacterEvent
    0x800ea3d4: onHitWithIceBall__Q24Koga22CharacterEventObserverFPQ24Koga14CharacterEvent
    0x800ea400: onHitWithWaterBall__Q24Koga22CharacterEventObserverFPQ24Koga14CharacterEvent
    
    0x800ea42c: onFishingBegin__Q24Koga22CharacterEventObserverFPQ24Koga14CharacterEvent
    0x800ea434: onPlayerLeftRoom__Q24Koga22CharacterEventObserverFPQ24Koga14CharacterEvent
    0x800ea43c: onPlayerEnteredRoom__Q24Koga22CharacterEventObserverFPQ24Koga14CharacterEvent
    0x800ea444: onPlayerTapped__Q24Koga22CharacterEventObserverFPQ24Koga14CharacterEvent
    0x800ea44c: FUN_800ea44c__Q24Koga22CharacterEventObserverFPQ24Koga14CharacterEvent
    
    # SDK Symbols
    # DVD
    0x801e2a08: __DVDInitWA
    0x801e2a48: __DVDInterruptHandler
    0x801e2d30: AlarmHandler_dvdlow
    0x801e2db4: AlarmHandlerForTimeout_dvdlow
    0x801e2e24: Read
    0x801e2f2c: SeekTwiceBeforeRead
    0x801e2fac: DVDLowRead
    0x801e3244: DVDLowSeek
    0x801e32cc: DVDLowWaitCoverClose
    0x801e32ec: DVDLowReadDiskID
    0x801e338c: DVDLowStopMotor
    0x801e3410: DVDLowRequestError
    0x801e3494: DVDLowInquiry
    0x801e3528: DVDLowAudioStream
    0x801e35b4: DVDLowRequestAudioStatus
    0x801e3634: DVDLowAudioBufferConfig
    0x801e36d0: DVDLowReset
    0x801e378c: DVDLowDoBreak
    0x801e3800: SetBreakAlarm
    0x801e3864: DVDLowBreak
    0x801e390c: DVDLowClearCallback
    0x801e3924: __DVDLowSetWAType
    0x801e3968: __DVDFSInit
    0x801e39a0: DVDConvertPathToEntrynum
    0x801e3c80: DVDOpen
    0x801e3d48: DVDClose
    0x801e3d6c: entryToPath
    0x801e3ecc: DVDGetCurrentDir
    0x801e3f90: DVDReadAsyncPrio
    0x801e4050: cbForReadAsync
    0x801e4080: DVDReadPrio
    0x801e4198: cbForReadSync
    0x801e41bc: DVDReadDir
    0x801e4260: DVDCloseDir
    0x801e4268: DVDPrepareStreamAsync
    0x801e4354: cbForPrepareStreamAsync
    0x801e4384: DVDInit
    0x801e4480: stateReadingFST
    0x801e44d4: cbForStateReadingFST
    0x801e4554: cbForStateError
    0x801e45fc: stateTimeout
    0x801e4698: stateGettingError
    0x801e46c0: CategorizeError
    0x801e4774: cbForStateGettingError
    0x801e4a08: cbForUnrecoveredError
    0x801e4a70: cbForUnrecoveredErrorRetry
    0x801e4b08: stateGoToRetry
    0x801e4b30: cbForStateGoToRetry
    0x801e4c88: stateCheckID
    0x801e4d6c: stateCheckID3
    0x801e4da0: stateCheckID2
    0x801e4dd8: cbForStateCheckID1
    0x801e4eec: cbForStateCheckID2
    0x801e4f90: cbForStateCheckID3
    0x801e508c: AlarmHandler_dvd
    0x801e50d0: stateCoverClosed
    0x801e519c: stateCoverClosed_CMD
    0x801e51cc: cbForStateCoverClosed
    0x801e523c: stateMotorStopped
    0x801e5264: cbForStateMotorStopped
    0x801e5348: stateReady
    0x801e5590: stateBusy
    0x801e5850: cbForStateBusy
    0x801e5e24: issueCommand
    0x801e5ee0: DVDReadAbsAsyncPrio
    0x801e5fbc: DVDReadAbsAsyncPrioForBS
    0x801e608c: DVDReadDiskID
    0x801e6160: DVDPrepareStreamAbsAync
    0x801e6224: DVDCancelStream
    0x801e62ec: DVDReset
    0x801e6330: DVDGetCommandBlockStatus
    0x801e637c: DVDGetDriveStatus
    0x801e6428: DVDCancelAsync
    0x801e6698: DVDCancel
    0x801e6744: cbForCancelSync
    0x801e6768: DVDGetCurrentDiskID
    0x801e6770: DVDCheckDisk
    0x801e6854: __DVDPrepareResetAsync
    0x801e6970: __DVDClearWaitingQueue
    0x801e69a8: __DVDPushWaitingQueue
    0x801e6a10: __DVDPopWaitingQueue
    0x801e6ab0: __DVDCheckWaitingQueue
    0x801e6b08: __DVDDequeueWaitingQueue
    0x801e6b68: __DVDStoreErrorCode
    0x801e6cc0: DVDCompareDiskID
    0x801e6d98: __fstLoad
    
    # VI
    0x801e6ee8: __VIRetraceHandler
    0x801e70f8: VISetPreRetraceCallback
    0x801e713c: getTiming
    0x801e71a4: __VIInit
    0x801e738c: VIInit
    0x801e77c0: VIWaitForRetrace
    0x801e7814: setFbbRegs
    0x801e7ae8: setVerticalRegs
    0x801e7c88: VIConfigure
    0x801e8338: VIFlush
    0x801e843c: VISetNextFrameBuffer
    0x801e84a8: VISetBlack
    0x801e8524: VIGetRetraceCount
    0x801e852c: getCurrentFieldEvenOdd
    0x801e85e8: VIGetNextField
    0x801e86dc: VIGetScanMode
    0x801e86e8: VIGetDTVStatus
    